name: Kaniko Action
description: Invoke Kankiko as a container to build a container image
author: Corey Woodcox

# Define your inputs here.
inputs:
  image:
    # TODO: This should support multiple values, like kaniko does
    description: "The name/tags of the desired image (ex: ghcr.io/cwoodcox/my-image)"
    required: true

# Define your outputs here.
outputs:
  time:
    description: The time we greeted you

runs:
  using: docker
  image: docker://gcr.io/kaniko-project/executor:latest
  args:
    - --image ${{ inputs.image }}
